[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version="Cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
arbitrum = "https://arb1.arbitrum.io/rpc"
ethereum = "https://ethereum-rpc.publicnode.com"
